--MemberDao.getMember(int page)
SELECT * FROM (SELECT ROWNUM NUM, M.* FROM 
(SELECT * FROM MEMBERS ORDER BY REGDATE DESC) M)
WHERE NUM BETWEEN 11 AND 20;

SELECT * FROM (SELECT ROWNUM NUM, MEMBERS.* FROM MEMBERS ORDER BY REGDATE DESC)
WHERE NUM BETWEEN 11 AND 20;

SELECT C##SIST.MEMBERS.MID, C##SIST.NOTICES.TITLE, C##SIST.NOTICES.NAME,
  C##SIST.NOTICES.REGDATE, C##SIST.MEMBERS.AGE, C##SIST.MEMBERS.BIRTHDAY,
  C##SIST.NOTICES.HIT
  FROM
       C##SIST.MEMBERS RIGHT OUTER JOIN C##SIST.NOTICES ON C##SIST.MEMBERS.NAME = C##SIST.NOTICES.NAME
